version: '3.8'

services:
  server:
    build: .
    container_name: server
    volumes:
      - ./:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - server 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge