name: Deploy FastAPI to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem || exit 1
          chmod 600 private_key.pem

      - name: Deploy to GCP VM
        run: |
          # SSH into GCP VM and run deployment commands
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.GCP_VM_IP || '34.120.208.247' }} << 'EOF'
            cd fastapi-book-project || exit 1
            git pull origin main || exit 1
            source venv/bin/activate || exit 1
            pip install -r requirements.txt || exit 1
            sudo systemctl restart fastapi || { echo 'FastAPI restart failure'; exit 1; }
            sudo systemctl reload nginx || { echo 'NginX reload Failure'; exit 1; }
            echo "✅ Successful Deployment!"
          EOF