name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Ubuntu Server with Appleboy SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.SSH_USERNAME }}/fastapi-book-project || {echo "change directory failed"; exit 1;}
            git pull origin main || { echo "git pull failed"; exit 1;}
            docker-compose down -v || {echo "compose failed"; exit 1;}
            docker-compose up --build -d  || { echo "build failed"; exit 1;}
            echo "FastAPI Book Project deployed successfully"