name: Deploy to GCP Compute Engine

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app

      - name: Deploy to Compute Engine
        run: |
          gcloud compute ssh my-instance --zone us-central1-a --command "
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app &&
          docker stop fastapi-container || true &&
          docker run -d -p 8000:8000 --name fastapi-container gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app
          "